student_app/urls.py
from django.urls import path
from . import views

app_name = 'student_app'
app_name = 'university'


urlpatterns = [
path('students', views.index, name='students'),
path('student/<int:student_id>/', views.details , name='student'),
path('teachers', views.teachers, name='teachers'),
path('teachers/<int:teacher_id>/', views.teacher , name='teacher'),
path('teachers/<int:teacher_id>/', views.teacher , name='teacher'),
path('create_teacher', views.createNewTeacher, name='create_teacher'),
]

student_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('university/', include('student_app.urls'))
]

student_app/models.py
from django.db import models

class Student(models.Model):
	first_name = models.CharField(max_length=20)
	last_name = models.CharField(max_length=20)
	date_naissance = models.DateField()

	def __str__(self):
		return self.first_name


class Note(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	matiere = models.CharField(max_length=20)
	note = models.PositiveIntegerField(default=0)
	coefficient = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.matiere

class Teacher(models.Model):
	prenom = models.CharField(max_length=20)
	nom = models.CharField(max_length=20)
	email = models.EmailField()
	date_naissance = models.DateField()
	matiere = models.CharField(max_length=20)
	
	def __str__(self):
		return self.prenom

student_app/forms.py
from django import forms 
from student_app.models import Teacher

class TeacherForm(forms.ModelForm):
	class Meta:
		model = Teacher
		fields = ['prenom','nom', 'email', 'matiere','date_naissance']
		widgets = {
		'prenom': forms.TextInput(attrs={
			'id':'teacher-prenom',
			'placeholder':'Prenom',
			'required': True
			}),
		'nom': forms.TextInput(attrs={
			'id':'teacher-nom',
			'placeholder':'Nom',
			'required': True
			}),
		'email': forms.EmailInput(attrs={
			'id':'teacher-email',
			'placeholder':'Email',
			'required': True
			}),
		'matiere': forms.TextInput(attrs={
			'id':'teacher-matiere',
			'placeholder':'Matiere',
			'required': True
			}),
		'date_naissance': forms.DateInput(attrs={
			'id':'teacher-date_naissance',
			'placeholder':'Date de Naissance',
			'required': True
			})
		}
		

student_app/views.py
from django.shortcuts import render
from student_app.models import Student, Note, Teacher
from student_app.forms import TeacherForm
import datetime

def index(request):
    students = Student.objects.all()
    return render(request, 'students/index.html', {'students':students})

def details(request, student_id):
    student = Student.objects.get(id=student_id)
    return render(request,'students/details.html',{'student':student})

def teachers(request):
	teachers = Teacher.objects.all()[:10]
	return render(request, 'teachers/index.html', context={ 'teachers': teachers })

def teacher(request, teacher_id):
	teacher = Teacher.objects.get(id=teacher_id)
	return render(request, 'teachers/teacherDetails.html', context={ 'teacher': teacher })

def createNewTeacher(request):
	if request.method == 'POST':
		prenom = request.POST.get('prenom')
		nom = request.POST.get('nom')
		email = request.POST.get('email')
		matiere = request.POST.get('matiere')
		date_naissance = datetime.datetime.now()
		Teacher.objects.get_or_create(prenom=prenom, nom=nom, email=email,matiere=matiere, date_naissance=date_naissance)[0]


	return render(request, 'teachers/createTeacher.html', context={ 'createTeacher': TeacherForm() })

student_app/templates/students/details.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Profile of {{student.first_name}}</title>
</head>
<body>
<div class="container">
     <div class="row">
       <div class="col-8 offset-sm-2">
         <div class="card mt-5">
           <div class="card-header">
       <h2>Profile</h2>
              <p>{{ student.first_name }}</p>
              <p>{{ student.last_name }}</p>
              <p>{{ student.date_naissance }}</p>
         <a href="{% url 'student_app:students' %}" class='list-group-item list-group-item-action'>Revenir en Arrière</a>
  </div>
   </div>
  </div>
 </div>
</div>
</body>
</html>

student_app/templates/students/index.html
<!DOCTYPE html>
<html>
<head>
    <link rel=“stylesheet” href=“https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css” integrity=“sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO” crossorigin=“anonymous”>
    <title>Liste des etudiants</title>
</head>
<body>
    <div class=“container”>
      <div class=“list-group”>
             <div class=“col-8 offset-sm-2”>
                     <div class=“card mt-5">
                        {% for student in students %}
                        <div class=“list-group-item list-group-item-action”>
                            <a href="{% url 'student_app:student' student.id %}" class="list-group-item list-group-item-action">Cliquez</a><br>
                            {{student.first_name}}<hr>
                        </div>
                        {% endfor %}
    </div>
    </div>
    </div>
    </div>
</body>
</html>

student_app/templates/teachers/createTeacher.html
<!DOCTYPE html>
<html>
<head>
    <title>Add a new Teacher</title>
</head>
<body>

    <h1>Add a new Teacher</h1>
    <form action="create_teacher" method="POST">
        {{ createTeacher.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Send Teacher">
    </form>

</body>
</html>

student_app/templates/teachers/index.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Index</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th scope=“col”>ID</th>
                <th scope="col">Prenom</th>
                <th scope="col">Nom</th>
            </tr>
        </thead>
        <div>
        {% for teacher in teachers %}
            <tbody>
                <tr>
                    <th scope=“col”>{{ teacher.id }}</th>
                    <td scope="row">
                        <a href="{% url 'university:teacher' teacher.id %}">{{ teacher.prenom }}</a>
                    </td>
                    <td scope="row">{{ teacher.nom }}</td>
                </tr>
        {% endfor %}
        </div>
</body>
</html>

student_app/templates/teachers/teacherDetails.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{{ teacher.prenom }}</title>
</head>
<body>
	<div class="container">
	<div class="row">
		<div class="col-md-8">
  <h1>Product Details</h1>
  <h3>Prenom: {{ teacher.prenom }}</h3>
  <hr>
  <h3>Nom: {{ teacher.nom }}</h3>
  <hr>
</div>
</div>
</div>
</body>
</html>